version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_user_group_permission_docker:latest
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      - SECRET_KEY=EB94C941DCE1455DA48A2CE2F8BEAF50B98704B92B163544AD64DEDEB665C6A2
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  src:
  postgres_data: